### ISSUE TITLE
promote-master on multi module projects

### ISSUE THREAD

**Issue by SimonK15** [egineering-llc/gitflow-helper-maven-plugin#44]
I am trying to run a mvn deploy on a multi module project.
Used gitflow-helper-maven-plugin version is 1.5.0.

Project structure is like this:
parent-pom
- module a
- module b

When I do a mvn deploy on the development branch the staging to our nexus fails with 
a 400 - BadRequest error. Reason seems to be that the process tries to upload some module-catalog.txt file.

After some search I figured out this information seems to be created during 
AbstractGitflowBasedRepositoryMojo#attachArtifactCatalog which is called when 
PromoteMasterMojo#execute method is invoked.

The output on the commandline shows:
[INFO] No primary artifact to catalog, cataloging attached artifacts instead.

I added some additional output to the 'attachArtifactCatalog ' method and could verify
that the project.getAttachedArtifacts() does return an empty list. 
This ends up in the creation of an empty file, which is later uploaded by the maven-deploy-plugin.
As this file is empty, the request does not contain any data and thus is rejected by nexus.

I hope somebody here has an idea whether this is a configuration issue or whether this is bug in the plugin.

The javadoc in the PromoteMasterMojo does not specify anything about doing something on 
a devopment branch, but the execute handels this case the same way as for hotfixes and releases.

After removing the respective case statement I could at least build the module normally. 
I have yet to test what happens on hotfix or release branches.

Edit:
I forgot to mention that the upload of the catalog.txt happens before the sub modules are actually build.

**Comment by bvarner** [comment]
Yikes! This sounds like a bug in the plugin. I don't think I ever tested it on multi-module projects...

**Comment by bvarner** [comment]
Would you be able to create a small sample project (in a github repo) I could use as a starting point?

**Comment by SimonK15** [comment]
I have set up a simple project on github:
see https://github.com/SimonK15/test-multi-module/

The section with the nexus repositories is commented, there you need to add something.
When executing mvn clean deploy -Denv.GIT_BRANCH="origin/dev" the error should happen

(I verified this under windows only, there seems to some issue with passing parameters from within Jenkins (running on a centOS). I might add another ticket for this later.)

**Comment by towerworks** [comment]
Maybe this helps to isolate the issue: I am using the plugin on a big multi-module project without issue (on OSX and ubuntu, never tried on Windows), repo is Nexus 3.0.2-2.

I also tried SimonK15's sample project on OSX and it deployed like a charm.

**Comment by bvarner** [comment]
So I did some digging on this today, as I was working on another PR / issue....

Turns out, I've been running this plugin on a multi-module project from the very genesis of this plugin. I just happened to forget about it....  Oddly enough, I use OS X locally, and the build server for that project is jenkins on linux (RHEL).

I think there may be a difference between resolving things from `${env}` vs `-D` system properties on windows which doesn't manifest on a *nix system. Of course I don't have a test VM setup to run windows on to try this out. (I know, I know, bad developer...)

Could someone try setting it as a true windows environment property and then run the clean deploy? Does this only affect multi-module projects or is that just a red-herring?
